[API_KEYS]
OPENAI = "sk-proj-vRdTBGefsLb3meK196SzT3BlbkFJjoaxdPtm6vzKkononlyy"
GROQ = ""

[API_ENDPOINTS]
OLLAMA = ""
SEARXNG = "http://localhost:32768"

[GENERAL]
PORT = 3001
SIMILARITY_MEASURE = "cosine"
